export const SETOPEN_LOCALE = 'SETOPEN_LOCALE';
export const SET_DEFAULT_LOCALE = 'SET_DEFAULT_LOCALE';
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';
export const SET_LOCALES = 'SET_LOCALES';
